# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0003_auto_20160211_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name=b'Conteudo da p\xc3\xa1gina'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(verbose_name=b'Data publica\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=80, verbose_name=b'T\xc3\xadtulo'),
        ),
    ]
