# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0004_auto_20160213_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featureImage',
            field=models.ImageField(null=True, upload_to=b'artigos/%y/%m/%d'),
        ),
    ]
