# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0005_article_featureimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Conteudo da página'),
        ),
        migrations.AlterField(
            model_name='article',
            name='featureImage',
            field=models.ImageField(null=True, upload_to='artigos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(verbose_name='Data publicação'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Título'),
        ),
    ]
