# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0006_auto_20160215_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='featureImage',
        ),
    ]
