# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0008_article_imagefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imageHeight',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='article',
            name='imageWidth',
            field=models.IntegerField(default=100),
        ),
    ]
